# PPO Training Configuration for Traffic Intersection DRL - OPTIMIZED MODE

# Training Parameters - OPTIMIZED FOR QUANTIZED PARAMETERS
total_timesteps: 10000  # Increased due to faster convergence with quantized params
eval_freq: 1000         # Less frequent evaluation for speed
checkpoint_freq: 1000   # Less frequent checkpoints

# PPO Algorithm Parameters - OPTIMIZED FOR QUANTIZED ACTION SPACE
learning_rate: 5e-4     # Higher LR for quantized params
n_steps: 512            # Increased for better exploration with discrete actions
batch_size: 64          # Larger batch for stable training
n_epochs: 8             # More epochs for quantized parameter learning
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.01          # Small entropy bonus for exploration
vf_coef: 0.5
max_grad_norm: 0.5

# Simulation Configuration - FASTER EPISODES
sim_config:
  map: 'Town05'
  max_steps: 500      # Reduced from 2000
  spawn_rate: 0.8
  intersection_center: [-188.9, -89.7, 0.0]

# Reward Configuration - FIXED VALUES (not trainable)
reward_config:
  vehicle_exit_reward: 10.0      # FIXED: Not trainable
  throughput_bonus: 0.01         # FIXED: Not trainable
  acceleration_penalty_threshold: 3.0
  acceleration_penalty_factor: 2.0
  efficiency_bonus: 5.0
  collision_penalty: 100.0       # FIXED: Not trainable
  deadlock_penalty: 800.0        # FIXED: Not trainable
  step_penalty: 0.1

# OPTIMIZED: Only 8 trainable parameters instead of 18
nash_hyperparams:
  path_intersection_threshold:
    range: [2.5, 2.5]  # FIXED: Not trainable
    default: 2.5
    description: "Distance threshold for detecting path intersections (FIXED)"
  platoon_conflict_distance:
    range: [15.0, 15.0]  # FIXED: Not trainable
    default: 15.0
    description: "Distance at which platoons are considered in conflict (FIXED)"

# Training Schedule
schedule:
  warmup_steps: 50000
  decay_steps: 100000
  min_learning_rate: 1e-5

# Evaluation
evaluation:
  n_eval_episodes: 5
  eval_deterministic: true
  eval_render: false

# Logging
logging:
  tensorboard: false
  csv: true
  metrics_freq: 100
  save_freq: 1000

# OPTIMIZATION NOTES:
# - Action space reduced from 18 to 8 parameters (55% reduction)
# - Observation space reduced from 169 to 60 dimensions (65% reduction)
# - Only core parameters are trainable: bid_scale, eta_weight, platoon_bonus, junction_penalty,
#   speed_diff_modifier, max_participants_per_auction, ignore_vehicles_go, ignore_vehicles_platoon_leader
# - All other parameters are fixed for stability and faster training
